### ISSUE TITLE
Add advanced/extended CI for gocql

### ISSUE THREAD

**Issue by sylwiaszunejko** [scylladb/gocql#203]
Epic to track activities aiming to make the CI more reliable and efficient.

```[tasklist]
### Tasks
- [ ] make every PR to build [scylla-bench ](https://github.com/scylladb/scylla-bench) from a PR branch and run simple scylla-bench test
- [ ] for more complex PRs run more advanced tests from scylla-bench
- [ ] connect CI to jenkins
```

**Comment by sylwiaszunejko** [comment]
@roydahan

**Comment by sylwiaszunejko** [comment]
duplicate
